name: ecosystem
on:
  push:
    branches: [main, ci/hpm]
  workflow_dispatch:
jobs:
  http-proxy-middleware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v6
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm test:ecosystem http-proxy-middleware
